SUIT_SYMBOLS = {
    "major": "✦",
    "wands": "🜂",
    "cups": "🜄",
    "swords": "🜁",
    "pentacles": "🜃",
}

SUIT_NAMES_CN = {
    "major": "大阿尔卡那",
    "wands": "权杖",
    "cups": "圣杯",
    "swords": "宝剑",
    "pentacles": "星币",
}

SPREAD_POSITIONS = {
    "single": ["今日指引"],
    "three": ["过去", "现在", "未来"],
    "choice": ["选择 A 的能量", "选择 B 的能量"],
}

TAROT_DECK = [
    # ── MAJOR ARCANA ──────────────────────────────────────────────
    {
        "id": "major_00", "name": "The Fool", "name_cn": "愚者",
        "arcana": "major", "suit": "major", "number": 0,
        "keywords_upright": ["新开始", "天真", "冒险", "自由", "无限可能"],
        "keywords_reversed": ["鲁莽", "迷失方向", "幼稚", "逃避现实"],
        "element_desc": "风——流动性与突破，思维脱离已有框架的能量",
        "numerology_desc": "0：尚未做出任何选择之前的状态，潜能未被定义，既无失去也无获得",
        "astrology_desc": "天王星：打破常规的冲动，从既有轨道出走——不是因为知道终点，而是因为再待下去无法呼吸",
    },
    {
        "id": "major_01", "name": "The Magician", "name_cn": "魔法师",
        "arcana": "major", "suit": "major", "number": 1,
        "keywords_upright": ["意志力", "技能", "创造", "显化", "行动"],
        "keywords_reversed": ["操控", "欺骗", "才能浪费", "犹豫不决"],
        "element_desc": "风（水星属）——将内部想法转化为外部行动的桥梁",
        "numerology_desc": "1：原始意志的第一个动作，从无到有，一切工具都在手边",
        "astrology_desc": "水星：思维与工具，把一个想法转化成可操作步骤的能力",
    },
    {
        "id": "major_02", "name": "The High Priestess", "name_cn": "女祭司",
        "arcana": "major", "suit": "major", "number": 2,
        "keywords_upright": ["直觉", "潜意识", "神秘", "内在智慧", "耐心"],
        "keywords_reversed": ["压抑直觉", "秘密", "表面信息", "内心混乱"],
        "element_desc": "水——潜伏在表面之下，尚未被言语命名的感知层",
        "numerology_desc": "2：两极并立，尚未选择——表面之下有另一层，安静地存在着",
        "astrology_desc": "月亮：潜意识的节律，你感知到但说不清楚的那部分信息",
    },
    {
        "id": "major_03", "name": "The Empress", "name_cn": "皇后",
        "arcana": "major", "suit": "major", "number": 3,
        "keywords_upright": ["丰盛", "母性", "自然", "滋养", "创造力"],
        "keywords_reversed": ["依赖", "创意受阻", "过度保护", "不安全感"],
        "element_desc": "土（金星属）——通过接纳、滋养、陪伴而非控制来创造",
        "numerology_desc": "3：两极之后诞生第三方，创造力和生命力向外流动",
        "astrology_desc": "金星：愉悦与接纳，美和丰盛通过允许而非强迫来降临",
    },
    {
        "id": "major_04", "name": "The Emperor", "name_cn": "皇帝",
        "arcana": "major", "suit": "major", "number": 4,
        "keywords_upright": ["权威", "结构", "稳定", "领导力", "保护"],
        "keywords_reversed": ["专制", "僵化", "控制欲", "缺乏纪律"],
        "element_desc": "火——意志以结构和权威的方式外化",
        "numerology_desc": "4：四个角、稳固的地基，秩序被固化进现实",
        "astrology_desc": "白羊座：领头羊的能量，通过主动意志和清晰边界来建立秩序",
    },
    {
        "id": "major_05", "name": "The Hierophant", "name_cn": "教皇",
        "arcana": "major", "suit": "major", "number": 5,
        "keywords_upright": ["传统", "信仰", "教育", "制度", "道德指引"],
        "keywords_reversed": ["打破规则", "被限制", "质疑权威", "非传统"],
        "element_desc": "土——传统、制度和集体信仰作为价值根基",
        "numerology_desc": "5：奇数的不稳定性，但在这里是关于权威如何被传递和维系",
        "astrology_desc": "金牛座：价值与安全感，传统提供土地一样的稳定基础——也可能是束缚",
    },
    {
        "id": "major_06", "name": "The Lovers", "name_cn": "恋人",
        "arcana": "major", "suit": "major", "number": 6,
        "keywords_upright": ["爱", "选择", "价值观", "和谐", "深层连结"],
        "keywords_reversed": ["不和谐", "错误选择", "价值观冲突", "犹豫不决"],
        "element_desc": "风——两者之间的张力，一个需要用自我价值观做出的选择",
        "numerology_desc": "6：和谐不是天然状态，是选择之后主动维系的结果",
        "astrology_desc": "双子座：两面性，在两个可能性之间做出真正符合自己价值观的选择",
    },
    {
        "id": "major_07", "name": "The Chariot", "name_cn": "战车",
        "arcana": "major", "suit": "major", "number": 7,
        "keywords_upright": ["意志", "胜利", "掌控", "坚毅", "前进"],
        "keywords_reversed": ["失控", "方向迷失", "攻击性", "障碍重重"],
        "element_desc": "水——通过情感驱动和意志控制向前推进",
        "numerology_desc": "7：内省的数字，但这里是将内在动力向外输出，靠意志控制相互矛盾的力量",
        "astrology_desc": "巨蟹座：以保护本能和情感强度作为驱动力，向目标推进",
    },
    {
        "id": "major_08", "name": "Strength", "name_cn": "力量",
        "arcana": "major", "suit": "major", "number": 8,
        "keywords_upright": ["内在力量", "勇气", "耐心", "慈悲", "自信"],
        "keywords_reversed": ["不安全感", "自我怀疑", "情绪软弱", "强迫"],
        "element_desc": "火——柔性的力量，不是爆发而是持续的掌握",
        "numerology_desc": "8：数字8即∞，循环的柔性力量，不靠强迫而靠内在中心",
        "astrology_desc": "狮子座：通过爱和中心感而非强迫来驾驭力量，自信不是表演出来的",
    },
    {
        "id": "major_09", "name": "The Hermit", "name_cn": "隐者",
        "arcana": "major", "suit": "major", "number": 9,
        "keywords_upright": ["内省", "智慧", "独处", "寻求真相", "指引"],
        "keywords_reversed": ["孤立", "固执", "拒绝帮助", "迷失自我"],
        "element_desc": "土——精炼与分辨，独处是为了找到什么是本质的",
        "numerology_desc": "9：1到9的巅峰，内在智慧在边界处最为清晰",
        "astrology_desc": "处女座：分辨力，在独处中去除噪音，照亮真正重要的部分",
    },
    {
        "id": "major_10", "name": "Wheel of Fortune", "name_cn": "命运之轮",
        "arcana": "major", "suit": "major", "number": 10,
        "keywords_upright": ["转机", "命运", "机遇", "循环", "关键节点"],
        "keywords_reversed": ["坏运气", "抗拒改变", "外力干扰", "逆境"],
        "element_desc": "火（木星属）——运势的轮转，不受个人意志控制的更大周期",
        "numerology_desc": "10=1+0=1：旧周期彻底完成，新起点在关闭之后开启",
        "astrology_desc": "木星：扩展与变化，命运的轮转不按你的计划表走，它有自己的节奏",
    },
    {
        "id": "major_11", "name": "Justice", "name_cn": "正义",
        "arcana": "major", "suit": "major", "number": 11,
        "keywords_upright": ["公正", "真相", "因果", "诚实", "平衡"],
        "keywords_reversed": ["不公正", "失衡", "逃避责任", "自欺欺人"],
        "element_desc": "风——不是情感的公平，而是基于事实的清醒判断",
        "numerology_desc": "11=1+1：两个1对望，行动与其后果的等值关系",
        "astrology_desc": "天秤座：平衡是主动裁量的结果，不是自然产生的——需要看清事实本身",
    },
    {
        "id": "major_12", "name": "The Hanged Man", "name_cn": "倒吊人",
        "arcana": "major", "suit": "major", "number": 12,
        "keywords_upright": ["暂停", "放手", "新视角", "牺牲", "等待"],
        "keywords_reversed": ["拖延", "逃避", "无谓牺牲", "内心抗拒"],
        "element_desc": "水——在悬置中，平时看不见的东西浮现出来",
        "numerology_desc": "12=1+2=3：创造力以非常规的方式出现，悬停本身是一种产出",
        "astrology_desc": "海王星：溶解边界，暂停时表面下的东西会浮上来——前提是你愿意等待而非挣扎",
    },
    {
        "id": "major_13", "name": "Death", "name_cn": "死神",
        "arcana": "major", "suit": "major", "number": 13,
        "keywords_upright": ["结束", "转变", "过渡", "新生", "蜕变"],
        "keywords_reversed": ["抗拒改变", "停滞不前", "无法放手", "腐朽"],
        "element_desc": "水（天蝎属）——蜕变，彻底的终结是深层转化的前提",
        "numerology_desc": "13=1+3=4：旧结构完全瓦解后，新的地基才开始形成",
        "astrology_desc": "天蝎座：蜕变，不允许旧的形式继续存在——不是恐惧，而是不可回避的转化",
    },
    {
        "id": "major_14", "name": "Temperance", "name_cn": "节制",
        "arcana": "major", "suit": "major", "number": 14,
        "keywords_upright": ["平衡", "节制", "耐心", "融合", "目标感"],
        "keywords_reversed": ["失衡", "过度", "急躁", "不协调"],
        "element_desc": "火（射手属）——将对立能量整合而非压制，以流动达到更高目标",
        "numerology_desc": "14=1+4=5：成熟的5，不是用冲突解决张力，而是学会在两极之间流动",
        "astrology_desc": "射手座：整合对立视角，以更大的意义框架来容纳矛盾",
    },
    {
        "id": "major_15", "name": "The Devil", "name_cn": "恶魔",
        "arcana": "major", "suit": "major", "number": 15,
        "keywords_upright": ["束缚", "执念", "阴影", "物质", "依赖"],
        "keywords_reversed": ["解脱", "觉醒", "重获自由", "直面阴暗面"],
        "element_desc": "土（摩羯属）——物质和结构如何在不自知中成为束缚",
        "numerology_desc": "15=1+5=6：和谐的阴影面，表面关系下被压制或物化的部分",
        "astrology_desc": "摩羯座：权力与物质，当追求结构和掌控变成目的本身，会以什么形式困住你",
    },
    {
        "id": "major_16", "name": "The Tower", "name_cn": "塔",
        "arcana": "major", "suit": "major", "number": 16,
        "keywords_upright": ["突变", "颠覆", "真相揭示", "危机", "清除虚假"],
        "keywords_reversed": ["延迟崩塌", "轻微震荡", "恐惧改变", "避免灾难"],
        "element_desc": "火（火星属）——破坏性的冲力清除了虚假的结构",
        "numerology_desc": "16=1+6=7：内省积累的张力以突然外爆的方式释放",
        "astrology_desc": "火星：被打掉的是建立在不真实基础上的东西，破坏即清除",
    },
    {
        "id": "major_17", "name": "The Star", "name_cn": "星星",
        "arcana": "major", "suit": "major", "number": 17,
        "keywords_upright": ["希望", "信念", "更新", "灵感", "宁静"],
        "keywords_reversed": ["绝望", "沮丧", "失去信念", "与自我断连"],
        "element_desc": "风（水瓶属）——从宏观视角恢复，连结比孤立更真实",
        "numerology_desc": "17=1+7=8：力量在崩塌之后以平静的形式重新出现，循环仍在",
        "astrology_desc": "水瓶座：从整体视角俯瞰自己，你不是孤立的事件，有更大的连结在",
    },
    {
        "id": "major_18", "name": "The Moon", "name_cn": "月亮",
        "arcana": "major", "suit": "major", "number": 18,
        "keywords_upright": ["幻觉", "潜意识", "直觉", "恐惧", "不确定性"],
        "keywords_reversed": ["困惑消散", "真相浮现", "焦虑释放", "欺骗揭露"],
        "element_desc": "水（双鱼属）——潜意识的投影面，恐惧与期待混在一起",
        "numerology_desc": "18=1+8=9：接近完整却困在幻象中，穿越它才能完成这个周期",
        "astrology_desc": "双鱼座：你所看见的，哪些是现实，哪些是你的投影——月亮不制造幻象，它照出已有的",
    },
    {
        "id": "major_19", "name": "The Sun", "name_cn": "太阳",
        "arcana": "major", "suit": "major", "number": 19,
        "keywords_upright": ["成功", "喜悦", "活力", "光明", "积极"],
        "keywords_reversed": ["自我怀疑", "乐观受阻", "短暂快乐", "过于天真"],
        "element_desc": "火——核心自我以清晰的形式向外辐射",
        "numerology_desc": "19=1+9=10=1：新循环在完整展开后重新开始，自我回到中心",
        "astrology_desc": "太阳：你真正的中心，当它可见时，方向和能量会同时回来",
    },
    {
        "id": "major_20", "name": "Judgement", "name_cn": "审判",
        "arcana": "major", "suit": "major", "number": 20,
        "keywords_upright": ["觉醒", "回顾", "内在呼唤", "更新", "救赎"],
        "keywords_reversed": ["自我怀疑", "拒绝反思", "错误判断", "内疚自责"],
        "element_desc": "火（冥王星属）——来自内部的召唤，比日常身份更深的声音",
        "numerology_desc": "20=2+0=2：更高层的两极，不是外部选择而是内在应答",
        "astrology_desc": "冥王星：深层转化，一种更真实的自我正在敲门——你是否在听",
    },
    {
        "id": "major_21", "name": "The World", "name_cn": "世界",
        "arcana": "major", "suit": "major", "number": 21,
        "keywords_upright": ["完成", "整合", "成就", "圆满", "旅程终结"],
        "keywords_reversed": ["未竟之事", "走捷径", "延迟", "缺乏结局"],
        "element_desc": "土（土星属）——成就需要时间和边界才能成形，整合已经完成",
        "numerology_desc": "21=2+1=3：创造力以整合的方式完成了一个完整周期",
        "astrology_desc": "土星：时间与边界，旅程的完整闭合——是完成，不是终止",
    },
    # ── WANDS ─────────────────────────────────────────────────────
    {
        "id": "wands_01", "name": "Ace of Wands", "name_cn": "权杖王牌",
        "arcana": "minor", "suit": "wands", "number": 1,
        "keywords_upright": ["新起点", "灵感迸发", "创造力", "热情", "潜力"],
        "keywords_reversed": ["延误", "缺乏动力", "创意受阻", "虎头蛇尾"],
        "element_desc": "火（纯粹）——创造冲动在还未形成方向之前的状态",
        "numerology_desc": "王牌即1：原始的意志萌发，还没有形状，只有能量",
        "astrology_desc": "火元素起源，无特定星座对应——纯粹的可能性，尚未被任何方向承接",
    },
    {
        "id": "wands_02", "name": "Two of Wands", "name_cn": "权杖二",
        "arcana": "minor", "suit": "wands", "number": 2,
        "keywords_upright": ["计划", "远见", "决策", "探索", "进取心"],
        "keywords_reversed": ["犹豫不决", "计划受阻", "畏惧未知", "原地踏步"],
        "element_desc": "火——意志点燃之后，站在门槛上，两条路摆在面前",
        "numerology_desc": "2：两种可能相对，这是规划而非行动的节点，你在看向远方",
        "astrology_desc": "火星在白羊座（0°-10°）：最原始的冲劲开始进入战略思考阶段，但策略还未完全成形",
    },
    {
        "id": "wands_03", "name": "Three of Wands", "name_cn": "权杖三",
        "arcana": "minor", "suit": "wands", "number": 3,
        "keywords_upright": ["扩展", "等待结果", "远见", "合作", "远方机遇"],
        "keywords_reversed": ["延迟", "挫折", "回头路", "缺乏远见"],
        "element_desc": "火——已经出发，在扩展途中等待第一批结果",
        "numerology_desc": "3：已经离开了起点，但还没有抵达，是中途的停驻而非终点",
        "astrology_desc": "太阳在白羊座（10°-20°）：冲劲达到顶点，但方向是否清晰是接下来的核心问题",
    },
    {
        "id": "wands_04", "name": "Four of Wands", "name_cn": "权杖四",
        "arcana": "minor", "suit": "wands", "number": 4,
        "keywords_upright": ["庆祝", "家庭", "和谐", "稳定", "里程碑"],
        "keywords_reversed": ["不稳定", "延迟庆祝", "缺乏支持", "家庭矛盾"],
        "element_desc": "火——意志找到了暂时的落脚点，庆祝是必要的停顿",
        "numerology_desc": "4：四个角稳固，是一个里程碑，但不是终点",
        "astrology_desc": "金星在白羊座（20°-30°）：行动的能量与美、连结短暂交汇，这是休憩而非停止",
    },
    {
        "id": "wands_05", "name": "Five of Wands", "name_cn": "权杖五",
        "arcana": "minor", "suit": "wands", "number": 5,
        "keywords_upright": ["竞争", "冲突", "挑战", "差异", "激烈讨论"],
        "keywords_reversed": ["避免冲突", "达成协议", "内部摩擦", "虚耗精力"],
        "element_desc": "火——冲突是火元素扩张时不可避免的摩擦",
        "numerology_desc": "5：稳定结构被打破，差异和竞争浮出水面",
        "astrology_desc": "土星在狮子座（0°-10°）：自我表达遭遇外部阻力，摩擦是扩张前的必经过程",
    },
    {
        "id": "wands_06", "name": "Six of Wands", "name_cn": "权杖六",
        "arcana": "minor", "suit": "wands", "number": 6,
        "keywords_upright": ["胜利", "荣誉", "成功", "认可", "领导"],
        "keywords_reversed": ["骄傲受挫", "延迟成功", "缺乏认可", "私下成就"],
        "element_desc": "火——经过竞争之后获得外部认可的能量",
        "numerology_desc": "6：冲突之后主动维系的和谐，通过被看见而获得的稳定感",
        "astrology_desc": "木星在狮子座（10°-20°）：自我在扩张中获得确认，但认可也可能成为依赖",
    },
    {
        "id": "wands_07", "name": "Seven of Wands", "name_cn": "权杖七",
        "arcana": "minor", "suit": "wands", "number": 7,
        "keywords_upright": ["坚守阵地", "挑战", "坚毅", "竞争优势", "捍卫"],
        "keywords_reversed": ["筋疲力尽", "放弃", "不堪压力", "过度防御"],
        "element_desc": "火——用意志维持现有位置，从进攻转为防御",
        "numerology_desc": "7：向内的坚守，不再扩张，而是保卫已有的成果",
        "astrology_desc": "火星在狮子座（20°-30°）：火的能量转为防守模式，坚毅和疲惫同时存在",
    },
    {
        "id": "wands_08", "name": "Eight of Wands", "name_cn": "权杖八",
        "arcana": "minor", "suit": "wands", "number": 8,
        "keywords_upright": ["快速行动", "冲刺", "旅行", "消息", "势不可挡"],
        "keywords_reversed": ["延误", "受阻", "节奏失控", "沟通不畅"],
        "element_desc": "火——能量加速，推进力进入高峰",
        "numerology_desc": "8：循环的力量，速度和方向同时清晰",
        "astrology_desc": "水星在射手座（0°-10°）：思想与行动同频，信息和方向同时快速推进",
    },
    {
        "id": "wands_09", "name": "Nine of Wands", "name_cn": "权杖九",
        "arcana": "minor", "suit": "wands", "number": 9,
        "keywords_upright": ["坚韧", "警惕", "界限", "接近终点", "坚持到底"],
        "keywords_reversed": ["固执", "偏执", "疲惫放弃", "不敢信任"],
        "element_desc": "火——疲惫与警觉并存，接近终点时的最后坚守",
        "numerology_desc": "9：巅峰与边界，成功前的最后一道坎",
        "astrology_desc": "月亮在射手座（10°-20°）：在长期追求中，情绪需要稳定的锚点，警觉背后有疲惫",
    },
    {
        "id": "wands_10", "name": "Ten of Wands", "name_cn": "权杖十",
        "arcana": "minor", "suit": "wands", "number": 10,
        "keywords_upright": ["重担", "责任", "压力", "勤奋", "即将完成"],
        "keywords_reversed": ["放下重担", "分担责任", "精力耗尽", "过度承担"],
        "element_desc": "火——旧周期以沉重负担的形式完成",
        "numerology_desc": "10=1+0=1：旧周期的完成，但完成本身是一种重压",
        "astrology_desc": "土星在射手座（20°-30°）：自由探索的能量遭遇现实责任，这是完成的代价，不是失败",
    },
    {
        "id": "wands_11", "name": "Page of Wands", "name_cn": "权杖侍从",
        "arcana": "minor", "suit": "wands", "number": 11,
        "keywords_upright": ["探索", "热情", "好奇心", "新思想", "创意萌芽"],
        "keywords_reversed": ["鲁莽", "执行力不足", "注意力涣散", "缺乏方向"],
        "element_desc": "火/土——火能量的探索阶段，用实验和好奇接触行动力",
        "numerology_desc": "宫廷牌·侍从：能量的学习阶段，热情在找到方向之前先找到自己",
        "astrology_desc": "火元素的土性侧——用试探而非全速冲刺来接触火能量，学习多于行动",
    },
    {
        "id": "wands_12", "name": "Knight of Wands", "name_cn": "权杖骑士",
        "arcana": "minor", "suit": "wands", "number": 12,
        "keywords_upright": ["激情", "冒险", "行动", "充满活力", "自信"],
        "keywords_reversed": ["冲动莽撞", "缺乏计划", "急于求成", "心浮气躁"],
        "element_desc": "火/火——火能量全速推进，行动先于思考",
        "numerology_desc": "宫廷牌·骑士：能量的全速执行阶段，动力最强但方向最不稳定",
        "astrology_desc": "白羊-天蝎过渡期的火能量——冲动在顶峰，最大的风险是速度超过了判断",
    },
    {
        "id": "wands_13", "name": "Queen of Wands", "name_cn": "权杖王后",
        "arcana": "minor", "suit": "wands", "number": 13,
        "keywords_upright": ["独立", "魅力", "活力", "自信", "慷慨"],
        "keywords_reversed": ["自我中心", "嫉妒", "控制欲", "内耗"],
        "element_desc": "水/火——用接纳性的方式掌握和驾驭火能量，独立而有磁性",
        "numerology_desc": "宫廷牌·王后：成熟的接纳性能量，吸引而非追逐",
        "astrology_desc": "双鱼-白羊过渡——在冲动来临前就感知到了它，火能量在这里变得有方向",
    },
    {
        "id": "wands_14", "name": "King of Wands", "name_cn": "权杖国王",
        "arcana": "minor", "suit": "wands", "number": 14,
        "keywords_upright": ["领导力", "远见", "魅力", "创业精神", "荣誉"],
        "keywords_reversed": ["专横", "傲慢", "期望过高", "冲动失控"],
        "element_desc": "风/火——将激情转化为长远视野和领导架构",
        "numerology_desc": "宫廷牌·国王：成熟的主动性能量，方向感和驱动力同时稳定",
        "astrology_desc": "天蝎-射手过渡——深层的驱动力找到了扩展的方向，成为可持续的领导力",
    },
    # ── CUPS ──────────────────────────────────────────────────────
    {
        "id": "cups_01", "name": "Ace of Cups", "name_cn": "圣杯王牌",
        "arcana": "minor", "suit": "cups", "number": 1,
        "keywords_upright": ["新情感", "爱", "直觉", "创造力", "精神觉醒"],
        "keywords_reversed": ["情感压抑", "心灵空洞", "创造力受阻", "拒绝爱"],
        "element_desc": "水（纯粹）——情感最初始的状态，尚未流向任何地方的可能",
        "numerology_desc": "王牌即1：情感的第一个涌动，还没有具体形状，只有开放",
        "astrology_desc": "水元素起源，无特定星座——纯粹的情感容量，等待被填充",
    },
    {
        "id": "cups_02", "name": "Two of Cups", "name_cn": "圣杯二",
        "arcana": "minor", "suit": "cups", "number": 2,
        "keywords_upright": ["伙伴关系", "相互吸引", "和谐", "连结", "合一"],
        "keywords_reversed": ["分离", "失衡关系", "不和谐", "单恋"],
        "element_desc": "水——两者之间的情感识别与共鸣",
        "numerology_desc": "2：相遇，对彼此的识别，连结的第一个形状",
        "astrology_desc": "金星在巨蟹座（0°-10°）：情感中的吸引力，以温柔和保护的方式相遇",
    },
    {
        "id": "cups_03", "name": "Three of Cups", "name_cn": "圣杯三",
        "arcana": "minor", "suit": "cups", "number": 3,
        "keywords_upright": ["庆祝", "友谊", "社群", "合作", "共同喜悦"],
        "keywords_reversed": ["孤立", "过度放纵", "三角关系", "友谊摩擦"],
        "element_desc": "水——情感扩展为群体连结和共同的喜悦",
        "numerology_desc": "3：两极之外的第三方，情感从一对一扩展为群体的流动",
        "astrology_desc": "水星在巨蟹座（10°-20°）：情感通过语言和连结找到表达的出口",
    },
    {
        "id": "cups_04", "name": "Four of Cups", "name_cn": "圣杯四",
        "arcana": "minor", "suit": "cups", "number": 4,
        "keywords_upright": ["冷漠", "沉思", "内观", "错失机遇", "静默"],
        "keywords_reversed": ["新动力", "接受机遇", "走出孤立", "重燃热情"],
        "element_desc": "水——水停止流动，是向内收缩还是暂时保护",
        "numerology_desc": "4：情感固化，稳定背后有停滞，也有选择性的冷漠",
        "astrology_desc": "月亮在巨蟹座（20°-30°）：情感需求向内收缩，外部所提供的无法触及内心真正的需求",
    },
    {
        "id": "cups_05", "name": "Five of Cups", "name_cn": "圣杯五",
        "arcana": "minor", "suit": "cups", "number": 5,
        "keywords_upright": ["悲伤", "失落", "遗憾", "悲痛", "聚焦于失去"],
        "keywords_reversed": ["接受", "放手", "向前看", "宽恕与愈合"],
        "element_desc": "水——失去打破了稳定，悲伤是情感真实流动的证明",
        "numerology_desc": "5：失去之后的冲击，注意力固着在失去的部分，仍有留存的未被看见",
        "astrology_desc": "火星在天蝎座（0°-10°）：深层情感与失去的痛苦，强烈而难以回避，正视才能穿越",
    },
    {
        "id": "cups_06", "name": "Six of Cups", "name_cn": "圣杯六",
        "arcana": "minor", "suit": "cups", "number": 6,
        "keywords_upright": ["怀旧", "童年", "天真", "旧友", "美好回忆"],
        "keywords_reversed": ["停留过去", "失去天真", "无法前行", "理想化过去"],
        "element_desc": "水——情感在记忆中找到安慰，甜蜜与忧郁并存",
        "numerology_desc": "6：情感中的和谐来自某个更简单、更早的时间",
        "astrology_desc": "太阳在天蝎座（10°-20°）：记忆的能量在光照下浮现，是滋养还是逃避需要分辨",
    },
    {
        "id": "cups_07", "name": "Seven of Cups", "name_cn": "圣杯七",
        "arcana": "minor", "suit": "cups", "number": 7,
        "keywords_upright": ["幻想", "选项", "幻觉", "梦想", "想象力"],
        "keywords_reversed": ["清晰", "脱离幻想", "明确目标", "现实落地"],
        "element_desc": "水——情感在多个投影之间迷失，想象力超过了辨别力",
        "numerology_desc": "7：内省的数字，情感向内生出多个幻象，每一个都真实但不都可得",
        "astrology_desc": "金星在天蝎座（20°-30°）：欲望、美与幻觉交织，哪个是你真正想要的，而不只是想象中想要的",
    },
    {
        "id": "cups_08", "name": "Eight of Cups", "name_cn": "圣杯八",
        "arcana": "minor", "suit": "cups", "number": 8,
        "keywords_upright": ["离开", "寻求更深意义", "放弃", "转身而去", "追求内心"],
        "keywords_reversed": ["犹豫留下", "恐惧改变", "无法割舍", "逃避深层问题"],
        "element_desc": "水——察觉到这里已经完成了，主动离开，寻找更深的意义",
        "numerology_desc": "8：循环中的主动选择，离开不是失败，而是内心已经超出了现有容器",
        "astrology_desc": "土星在双鱼座（0°-10°）：感性在现实重量下承认某段关系或处境已走到了尽头",
    },
    {
        "id": "cups_09", "name": "Nine of Cups", "name_cn": "圣杯九",
        "arcana": "minor", "suit": "cups", "number": 9,
        "keywords_upright": ["满足", "愿望实现", "幸福", "知足", "感恩"],
        "keywords_reversed": ["不满足", "物质主义", "纵欲", "愿望落空"],
        "element_desc": "水——满足感达到顶点，愿望与现实短暂重合",
        "numerology_desc": "9：情感的巅峰，知足是一种主动的选择，不是外部给的",
        "astrology_desc": "木星在双鱼座（10°-20°）：情感扩展达到最大，愿望与现实短暂重合的时刻",
    },
    {
        "id": "cups_10", "name": "Ten of Cups", "name_cn": "圣杯十",
        "arcana": "minor", "suit": "cups", "number": 10,
        "keywords_upright": ["家庭幸福", "圆满爱情", "和谐", "长久满足", "祝福"],
        "keywords_reversed": ["家庭不和", "期望落差", "关系破裂", "表面和谐"],
        "element_desc": "水——情感周期完整完成，爱以持久连结的形式固化",
        "numerology_desc": "10=1+0=1：情感旅程的完整闭合，爱找到了它的归宿",
        "astrology_desc": "火星在双鱼座（20°-30°）：情感能量在完成时停止向外寻求，是落幕，也是持续",
    },
    {
        "id": "cups_11", "name": "Page of Cups", "name_cn": "圣杯侍从",
        "arcana": "minor", "suit": "cups", "number": 11,
        "keywords_upright": ["创意消息", "直觉感知", "敏感", "好奇", "情感探索"],
        "keywords_reversed": ["情感不成熟", "逃避现实", "情绪化", "幼稚冲动"],
        "element_desc": "水/土——情感直觉初次打开，以好奇而非控制来接触感受",
        "numerology_desc": "宫廷牌·侍从：情感的探索阶段，敏感性比成熟的处理能力先到来",
        "astrology_desc": "水象星座的土性侧——用好奇、开放的姿态接触情感，不急于理解或解决",
    },
    {
        "id": "cups_12", "name": "Knight of Cups", "name_cn": "圣杯骑士",
        "arcana": "minor", "suit": "cups", "number": 12,
        "keywords_upright": ["追随内心", "浪漫", "魅力", "诗意", "理想主义"],
        "keywords_reversed": ["情绪不稳", "逃避", "欺骗", "爱情幻想破灭"],
        "element_desc": "火/水——情感能量进入行动，追随心的指引而动",
        "numerology_desc": "宫廷牌·骑士：情感的全速执行，浪漫与理想主义在顶点，方向感仍依赖感觉",
        "astrology_desc": "双子-巨蟹过渡——用行动和语言追随情感，美丽且容易受挫",
    },
    {
        "id": "cups_13", "name": "Queen of Cups", "name_cn": "圣杯王后",
        "arcana": "minor", "suit": "cups", "number": 13,
        "keywords_upright": ["同理心", "直觉", "关怀", "情感支持", "内省"],
        "keywords_reversed": ["情绪不稳", "自我忽视", "失去界限", "情感操控"],
        "element_desc": "水/水——情感的深度接纳，同理心成为核心能力",
        "numerology_desc": "宫廷牌·王后：成熟的情感接纳，感受他人如同感受自己，需要界限保护",
        "astrology_desc": "天秤-天蝎过渡——以深度理解驾驭水能量，同理心是强大的，也需要有边界",
    },
    {
        "id": "cups_14", "name": "King of Cups", "name_cn": "圣杯国王",
        "arcana": "minor", "suit": "cups", "number": 14,
        "keywords_upright": ["情感成熟", "同情", "外交", "平衡", "智慧领导"],
        "keywords_reversed": ["情感操控", "压抑感情", "冷漠", "情绪爆发"],
        "element_desc": "风/水——用理性和距离来驾驭情感，情感成熟而不被淹没",
        "numerology_desc": "宫廷牌·国王：将情感转化为稳定的领导力，感受与判断同时在场",
        "astrology_desc": "双子-巨蟹过渡——用智识来容纳情感，是情感的成熟，不是压制",
    },
    # ── SWORDS ────────────────────────────────────────────────────
    {
        "id": "swords_01", "name": "Ace of Swords", "name_cn": "宝剑王牌",
        "arcana": "minor", "suit": "swords", "number": 1,
        "keywords_upright": ["突破", "清晰", "真相", "行动", "思想力量"],
        "keywords_reversed": ["思想混乱", "缺乏清晰", "残酷真相", "决策困难"],
        "element_desc": "风（纯粹）——思想最锋利的起点，清晰与切割同时存在",
        "numerology_desc": "王牌即1：思维的第一个清晰动作，还未被使用，所有可能性都在",
        "astrology_desc": "风元素起源，无特定星座——纯粹的认知力，等待被运用",
    },
    {
        "id": "swords_02", "name": "Two of Swords", "name_cn": "宝剑二",
        "arcana": "minor", "suit": "swords", "number": 2,
        "keywords_upright": ["僵局", "选择困境", "回避", "心理防御", "暂时平衡"],
        "keywords_reversed": ["做出选择", "减少焦虑", "信息明朗", "冲破僵局"],
        "element_desc": "风——两种想法相持不下，蒙眼是回避，不是中立",
        "numerology_desc": "2：两极并立，思维上的僵局，选择需要信息但信息被遮住了",
        "astrology_desc": "月亮在天秤座（0°-10°）：情感上的犹豫妨碍了理性判断，蒙住眼是暂时保护，也是延迟问题",
    },
    {
        "id": "swords_03", "name": "Three of Swords", "name_cn": "宝剑三",
        "arcana": "minor", "suit": "swords", "number": 3,
        "keywords_upright": ["心碎", "悲伤", "拒绝", "背叛", "痛苦"],
        "keywords_reversed": ["原谅", "愈合", "走出痛苦", "重新振作"],
        "element_desc": "风——真相的揭示，思维切开了情感最脆弱的部分",
        "numerology_desc": "3：第三方的闯入或事实的揭露，两极的稳定被第三个元素打破",
        "astrology_desc": "土星在天秤座（10°-20°）：现实的重量揭示了关系中无法承受的部分，痛苦是清晰的代价",
    },
    {
        "id": "swords_04", "name": "Four of Swords", "name_cn": "宝剑四",
        "arcana": "minor", "suit": "swords", "number": 4,
        "keywords_upright": ["休息", "静养", "冥想", "暂停", "恢复元气"],
        "keywords_reversed": ["重新出发", "内心不安", "被迫暂停", "拒绝休息"],
        "element_desc": "风——思维的停歇，不是失败，是必要的重置",
        "numerology_desc": "4：结构的短暂休整，在重新出发之前需要归零",
        "astrology_desc": "木星在天秤座（20°-30°）：在短暂的和平中恢复判断力，这是战略性的退出，不是软弱",
    },
    {
        "id": "swords_05", "name": "Five of Swords", "name_cn": "宝剑五",
        "arcana": "minor", "suit": "swords", "number": 5,
        "keywords_upright": ["冲突", "失败", "紧张", "胜利的代价", "自私"],
        "keywords_reversed": ["和解", "化解矛盾", "道歉", "放下争斗"],
        "element_desc": "风——冲突的代价超过了胜利的意义",
        "numerology_desc": "5：差异和冲突在风元素中以最锋利的方式显现",
        "astrology_desc": "金星在水瓶座（0°-10°）：用冷漠和距离处理冲突，赢了这局但损了关系",
    },
    {
        "id": "swords_06", "name": "Six of Swords", "name_cn": "宝剑六",
        "arcana": "minor", "suit": "swords", "number": 6,
        "keywords_upright": ["过渡", "离开困境", "平静过渡", "旅行", "新阶段"],
        "keywords_reversed": ["难以前行", "未解决的过去", "停滞", "拒绝离开"],
        "element_desc": "风——从动荡到平静的过渡，方向已有，水面仍有波纹",
        "numerology_desc": "6：思维找到了离开的路径，和谐来自主动离开，而非消除冲突",
        "astrology_desc": "水星在水瓶座（10°-20°）：理性帮助从混乱中找到出路，距离带来新的视角",
    },
    {
        "id": "swords_07", "name": "Seven of Swords", "name_cn": "宝剑七",
        "arcana": "minor", "suit": "swords", "number": 7,
        "keywords_upright": ["欺骗", "策略", "单独行动", "逃避", "不诚实"],
        "keywords_reversed": ["揭露欺骗", "承认错误", "归还", "面对后果"],
        "element_desc": "风——独行的策略，但孤立的聪明可能是自欺欺人",
        "numerology_desc": "7：向内的独行，思维选择了单独的路径，是策略也是逃避",
        "astrology_desc": "月亮在水瓶座（20°-30°）：情感被理性化为策略，但回避真实脆弱的代价正在累积",
    },
    {
        "id": "swords_08", "name": "Eight of Swords", "name_cn": "宝剑八",
        "arcana": "minor", "suit": "swords", "number": 8,
        "keywords_upright": ["束缚感", "限制", "自我禁锢", "无助", "困境"],
        "keywords_reversed": ["解脱束缚", "重获自由", "挑战信念", "自我赋权"],
        "element_desc": "风——思维本身成为了束缚，绳子不是外部绑上的",
        "numerology_desc": "8：循环的力量，但在这里是循环的困境，每个逃脱的念头都被另一个想法绕回来",
        "astrology_desc": "木星在双子座（0°-10°）：信息和选项越多反而越无法行动，思维扩张造成瘫痪",
    },
    {
        "id": "swords_09", "name": "Nine of Swords", "name_cn": "宝剑九",
        "arcana": "minor", "suit": "swords", "number": 9,
        "keywords_upright": ["焦虑", "恐惧", "噩梦", "绝望", "内心折磨"],
        "keywords_reversed": ["走出黑暗", "寻求帮助", "减轻焦虑", "理性看待恐惧"],
        "element_desc": "风——焦虑是过度思考的极限状态，在黑暗中旋转的念头",
        "numerology_desc": "9：思维的巅峰与暗面，智识到达边界时会以恐惧的形式倒灌",
        "astrology_desc": "火星在双子座（10°-20°）：思维在紧张中持续运转，找不到关停键，越想越大",
    },
    {
        "id": "swords_10", "name": "Ten of Swords", "name_cn": "宝剑十",
        "arcana": "minor", "suit": "swords", "number": 10,
        "keywords_upright": ["结局", "背叛", "危机", "彻底失败", "触底反弹"],
        "keywords_reversed": ["重新振作", "最坏已过", "无法逃避的终结", "放下执念"],
        "element_desc": "风——旧思维的彻底终结，是最坏也是最清晰的时刻",
        "numerology_desc": "10=1+0=1：旧周期以最剧烈的方式关闭，触底之后只剩一个方向",
        "astrology_desc": "太阳在双子座（20°-30°）：双子的分裂思维在极点崩塌，清晰与结束同时到来",
    },
    {
        "id": "swords_11", "name": "Page of Swords", "name_cn": "宝剑侍从",
        "arcana": "minor", "suit": "swords", "number": 11,
        "keywords_upright": ["好奇", "警觉", "聪明", "新想法", "求知欲"],
        "keywords_reversed": ["流言蜚语", "冲动", "表里不一", "轻率言辞"],
        "element_desc": "风/土——思维的探索阶段，用问题而非答案来接触世界",
        "numerology_desc": "宫廷牌·侍从：思维的学习阶段，好奇心和敏锐性先于判断力",
        "astrology_desc": "风象星座的土性侧——观察、记录、收集信息，行动之前先看清楚",
    },
    {
        "id": "swords_12", "name": "Knight of Swords", "name_cn": "宝剑骑士",
        "arcana": "minor", "suit": "swords", "number": 12,
        "keywords_upright": ["野心", "行动导向", "直接", "快速思维", "果敢"],
        "keywords_reversed": ["鲁莽", "冲动行事", "破坏性", "言辞伤人"],
        "element_desc": "火/风——思维进入全速行动，话语像剑一样直接",
        "numerology_desc": "宫廷牌·骑士：思维的全速执行，速度最快但也最容易越界",
        "astrology_desc": "摩羯-水瓶过渡的风能量——意志与逻辑的高速组合，直接高效，也容易伤人",
    },
    {
        "id": "swords_13", "name": "Queen of Swords", "name_cn": "宝剑王后",
        "arcana": "minor", "suit": "swords", "number": 13,
        "keywords_upright": ["独立", "清晰", "直接", "公平", "洞察力"],
        "keywords_reversed": ["冷漠", "苦涩", "刻薄", "孤立自我"],
        "element_desc": "水/风——情感经历之后的清醒，理性中有深度",
        "numerology_desc": "宫廷牌·王后：成熟的判断力来自亲历而非理论，清晰是痛苦之后的产物",
        "astrology_desc": "处女-天秤过渡——分辨能力来自真实经历，直接不是冷漠，是尊重",
    },
    {
        "id": "swords_14", "name": "King of Swords", "name_cn": "宝剑国王",
        "arcana": "minor", "suit": "swords", "number": 14,
        "keywords_upright": ["理性权威", "清晰思维", "真相", "道德", "公正判断"],
        "keywords_reversed": ["操控", "暴政", "滥用权力", "冷酷无情"],
        "element_desc": "风/风——思维的最高权威，以清晰和公正为核心",
        "numerology_desc": "宫廷牌·国王：将理性转化为原则和权威，判断以事实为基础，不受情绪干扰",
        "astrology_desc": "摩羯-水瓶过渡——将逻辑和结构转化为权威和治理，真相是最高标准",
    },
    # ── PENTACLES ─────────────────────────────────────────────────
    {
        "id": "pentacles_01", "name": "Ace of Pentacles", "name_cn": "星币王牌",
        "arcana": "minor", "suit": "pentacles", "number": 1,
        "keywords_upright": ["新机遇", "繁荣", "物质资源", "新起点", "显化"],
        "keywords_reversed": ["错失机遇", "计划失败", "物质损失", "根基不稳"],
        "element_desc": "土（纯粹）——物质世界的第一颗种子，尚未落地生根",
        "numerology_desc": "王牌即1：物质可能性的起源，资源和机遇在最初始的状态",
        "astrology_desc": "土元素起源，无特定星座——纯粹的物质潜能，等待被播种",
    },
    {
        "id": "pentacles_02", "name": "Two of Pentacles", "name_cn": "星币二",
        "arcana": "minor", "suit": "pentacles", "number": 2,
        "keywords_upright": ["灵活适应", "多重优先", "时间管理", "平衡", "游刃有余"],
        "keywords_reversed": ["失衡", "超负荷", "混乱", "优先级错乱"],
        "element_desc": "土——两个球同时保持平衡，是灵活而非固定的稳定",
        "numerology_desc": "2：两者同时在场，平衡不是静止，而是持续的动态调整",
        "astrology_desc": "木星在摩羯座（0°-10°）：扩展的能量遭遇结构的约束，灵活适应是关键",
    },
    {
        "id": "pentacles_03", "name": "Three of Pentacles", "name_cn": "星币三",
        "arcana": "minor", "suit": "pentacles", "number": 3,
        "keywords_upright": ["团队合作", "技能建设", "学习", "合作实现", "认可"],
        "keywords_reversed": ["缺乏合作", "平庸之作", "学习受阻", "孤军奋战"],
        "element_desc": "土——技能通过合作找到更大的落地空间",
        "numerology_desc": "3：三方协作，个人技能在集体结构中被放大",
        "astrology_desc": "火星在摩羯座（10°-20°）：行动力与专业性结合，努力在具体结构中获得认可",
    },
    {
        "id": "pentacles_04", "name": "Four of Pentacles", "name_cn": "星币四",
        "arcana": "minor", "suit": "pentacles", "number": 4,
        "keywords_upright": ["保守稳定", "控制", "积累", "安全感", "守护"],
        "keywords_reversed": ["吝啬", "执念于物质", "恐惧失去", "过度控制"],
        "element_desc": "土——把稳定抓得太紧的时候，安全感变成了禁锢",
        "numerology_desc": "4：四角固定，稳定与执念的临界点",
        "astrology_desc": "太阳在摩羯座（20°-30°）：结构和积累达到顶点，控制是保护还是恐惧失去，需要自问",
    },
    {
        "id": "pentacles_05", "name": "Five of Pentacles", "name_cn": "星币五",
        "arcana": "minor", "suit": "pentacles", "number": 5,
        "keywords_upright": ["财务困难", "物质匮乏", "孤立", "困难时期", "不安全感"],
        "keywords_reversed": ["走出困境", "获得帮助", "恢复", "看到希望"],
        "element_desc": "土——物质上的匮乏暴露出内在的孤立感",
        "numerology_desc": "5：稳定结构被打破，匮乏和孤立同时出现",
        "astrology_desc": "水星在金牛座（0°-10°）：关于资源的焦虑需要通过说出来和寻求信息来缓解",
    },
    {
        "id": "pentacles_06", "name": "Six of Pentacles", "name_cn": "星币六",
        "arcana": "minor", "suit": "pentacles", "number": 6,
        "keywords_upright": ["慷慨", "给予与接受", "公平", "分享", "平衡交换"],
        "keywords_reversed": ["自私", "债务", "不平等", "有条件付出"],
        "element_desc": "土——给予与接受的流动，和谐来自平等而非施舍",
        "numerology_desc": "6：和谐通过主动的给予与接受来维持，交换是否真的平等",
        "astrology_desc": "月亮在金牛座（10°-20°）：安全感通过物质的分享来表达——给与接受都需要尊严",
    },
    {
        "id": "pentacles_07", "name": "Seven of Pentacles", "name_cn": "星币七",
        "arcana": "minor", "suit": "pentacles", "number": 7,
        "keywords_upright": ["等待收获", "评估进展", "耐心", "长远投资", "可持续"],
        "keywords_reversed": ["不耐烦", "低回报", "缺乏长远规划", "三心二意"],
        "element_desc": "土——已经播种，在等待收获，停下来评估是必要的",
        "numerology_desc": "7：等待的数字，内省是为了判断当前投入是否值得继续",
        "astrology_desc": "土星在金牛座（20°-30°）：耐心是必要的，但这个等待是否值得需要诚实地评估",
    },
    {
        "id": "pentacles_08", "name": "Eight of Pentacles", "name_cn": "星币八",
        "arcana": "minor", "suit": "pentacles", "number": 8,
        "keywords_upright": ["勤奋", "专注", "技能精进", "细节", "工匠精神"],
        "keywords_reversed": ["缺乏动力", "质量低下", "完美主义陷阱", "重复乏味"],
        "element_desc": "土——力量来自重复与细节的积累，工匠精神",
        "numerology_desc": "8：循环中的精进，每一次重复都在加深能力",
        "astrology_desc": "太阳在处女座（0°-10°）：处女座的精确性在光照下成为核心工作状态，精进本身是目的",
    },
    {
        "id": "pentacles_09", "name": "Nine of Pentacles", "name_cn": "星币九",
        "arcana": "minor", "suit": "pentacles", "number": 9,
        "keywords_upright": ["富足", "独立", "自给自足", "优雅", "感恩"],
        "keywords_reversed": ["财务挫折", "过度依赖", "物质主义", "表面光鲜"],
        "element_desc": "土——独立与物质丰盛同时达到高位",
        "numerology_desc": "9：物质的巅峰，通过自己的努力实现的丰盛，不依赖他人",
        "astrology_desc": "金星在处女座（10°-20°）：美和满足通过精心照料自己来获得，独立是这里最大的礼物",
    },
    {
        "id": "pentacles_10", "name": "Ten of Pentacles", "name_cn": "星币十",
        "arcana": "minor", "suit": "pentacles", "number": 10,
        "keywords_upright": ["财富", "遗产", "家庭稳定", "长久成功", "传承"],
        "keywords_reversed": ["财务失败", "家庭不和", "失去遗产", "根基动摇"],
        "element_desc": "土——物质周期完整完成，成就以传承形式延续",
        "numerology_desc": "10=1+0=1：物质旅程的完整闭合，个人积累转化为持续的遗产",
        "astrology_desc": "水星在处女座（20°-30°）：细节和长远规划将个人积累固化为可延续的结构",
    },
    {
        "id": "pentacles_11", "name": "Page of Pentacles", "name_cn": "星币侍从",
        "arcana": "minor", "suit": "pentacles", "number": 11,
        "keywords_upright": ["野心", "新机遇", "踏实学习", "可靠", "目标感"],
        "keywords_reversed": ["缺乏进展", "学习受阻", "不切实际", "分心散漫"],
        "element_desc": "土/土——土能量的学习阶段，踏实且专注，基础还在建立中",
        "numerology_desc": "宫廷牌·侍从：物质能量的探索阶段，目标感清晰但经验还在积累",
        "astrology_desc": "土象星座的土性侧——用耐心和细心来积累实质，不急于求成",
    },
    {
        "id": "pentacles_12", "name": "Knight of Pentacles", "name_cn": "星币骑士",
        "arcana": "minor", "suit": "pentacles", "number": 12,
        "keywords_upright": ["刻苦努力", "可靠", "坚持", "负责任", "脚踏实地"],
        "keywords_reversed": ["懈怠", "停滞", "固执保守", "缺乏灵活性"],
        "element_desc": "火/土——土能量的推进，以稳定和可靠代替速度",
        "numerology_desc": "宫廷牌·骑士：物质能量的全速执行，可靠而持续，方向是稳定的",
        "astrology_desc": "狮子-处女过渡——将激情转化为精确行动，负责任地推进",
    },
    {
        "id": "pentacles_13", "name": "Queen of Pentacles", "name_cn": "星币王后",
        "arcana": "minor", "suit": "pentacles", "number": 13,
        "keywords_upright": ["务实", "滋养", "家庭", "财务安全", "丰盛慷慨"],
        "keywords_reversed": ["工作生活失衡", "自我忽视", "物质主义", "过度控制"],
        "element_desc": "水/土——用关怀和滋养来驾驭土能量，物质中有温度",
        "numerology_desc": "宫廷牌·王后：成熟的物质接纳，照料自己和他人的能力同时稳定",
        "astrology_desc": "射手-摩羯过渡——将宏观视野落实为具体的照料，务实且有爱",
    },
    {
        "id": "pentacles_14", "name": "King of Pentacles", "name_cn": "星币国王",
        "arcana": "minor", "suit": "pentacles", "number": 14,
        "keywords_upright": ["安全稳固", "财务掌控", "权威", "踏实成功", "慷慨富足"],
        "keywords_reversed": ["挥霍无度", "停滞守旧", "贪婪", "过于物质化"],
        "element_desc": "风/土——将土能量转化为长远规划和商业智慧",
        "numerology_desc": "宫廷牌·国王：物质的最高权威，将积累转化为稳定的财富和影响力",
        "astrology_desc": "白羊-金牛过渡——将行动力转化为持续积累的能力，财富是判断力的产物",
    },
]

assert len(TAROT_DECK) == 78, f"Deck should have 78 cards, got {len(TAROT_DECK)}"
